# fly.toml app configuration file generated for ember-rendezvous on 2026-04-04T17:49:17-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ember-rendezvous'
primary_region = 'iad'

[build]

[env]
  RUST_LOG = 'ember_rendezvous=info'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
