//! Clock-driven bandwidth caps — eMule's "day and night limits".
//!
//! A schedule is an ordered list of rules. Each names a set of weekdays, a
//! window of local wall-clock time, and the upload/download caps that apply
//! inside it. **The first matching rule wins**; when none matches, the manual
//! limits from Settings apply unchanged. Order-as-priority is the only
//! resolution that stays predictable once windows overlap, and for the common
//! non-overlapping weekday/weekend pair it never comes up.
//!
//! Evaluation is pure and takes the weekday and minute-of-day as arguments, so
//! every window shape can be tested without a clock. [`local_now`] is the only
//! function here that reads one.
//!
//! Times are **local**, not UTC: a rule that says "throttle from 09:00" means
//! nine in the morning where the user is. That also means a DST shift can make
//! a window an hour shorter or longer on the two days a year it moves, which is
//! the same thing every other wall-clock scheduler does and is what a user
//! reading "09:00" expects.

use serde::{Deserialize, Serialize};

/// Minutes in a day. A window's exclusive end may equal this ("until
/// midnight"), which is why the end is stored as `1..=1440` rather than as a
/// minute-of-day.
pub const MINUTES_PER_DAY: u16 = 1440;

/// Ceiling on stored rules. Generous next to any real timetable (a per-day
/// morning/evening split is 14) and small enough that evaluating the list once
/// a second costs nothing.
pub const MAX_SCHEDULE_RULES: usize = 32;

/// Ceiling on a rule's display label, in characters.
pub const MAX_RULE_LABEL_CHARS: usize = 48;

/// Ceiling on a rule id, in bytes. Ids are generated by the UI and only ever
/// used to match a rule against the currently-active one.
pub const MAX_RULE_ID_BYTES: usize = 64;

/// Every weekday bit set: Monday (bit 0) through Sunday (bit 6).
pub const ALL_DAYS: u8 = 0b0111_1111;

fn default_true() -> bool {
    true
}

/// One window of the bandwidth timetable.
///
/// `start_minute` / `end_minute` are minutes from local midnight. When
/// `end_minute <= start_minute` the window crosses midnight, and `days` names
/// the day the window **opens** — so `Mon 22:00 → 06:00` runs Monday evening
/// into Tuesday morning, and selecting only Monday is enough to express it.
#[derive(Clone, Debug, Serialize, Deserialize, PartialEq, Eq)]
pub struct BandwidthScheduleRule {
    /// Stable identity, generated by the UI. Only used to tell the UI which
    /// rule is in force right now.
    pub id: String,
    #[serde(default = "default_true")]
    pub enabled: bool,
    /// Optional human label ("Work hours", "Overnight"). Empty is fine — the
    /// UI falls back to rendering the window itself.
    #[serde(default)]
    pub label: String,
    /// Weekday bitmask: bit 0 = Monday … bit 6 = Sunday.
    pub days: u8,
    /// Inclusive window start, minutes from local midnight (`0..=1439`).
    pub start_minute: u16,
    /// Exclusive window end, minutes from local midnight (`1..=1440`).
    pub end_minute: u16,
    /// Upload cap in bytes/sec while this rule is in force. `0` is unlimited,
    /// matching `AppSettings::max_upload_speed`.
    pub max_upload_speed: u64,
    /// Download cap in bytes/sec while this rule is in force. `0` is unlimited.
    pub max_download_speed: u64,
}

/// The rule currently in force, flattened for the UI and for the runtime
/// status event.
#[derive(Clone, Debug, Default, Serialize, Deserialize, PartialEq, Eq)]
pub struct ActiveScheduleRule {
    pub id: String,
    pub label: String,
    /// Exclusive end of the window in force, minutes from local midnight. The
    /// UI renders this as "until 08:00".
    pub end_minute: u16,
}

/// What the schedule resolves to right now.
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct ResolvedLimits {
    pub max_upload_speed: u64,
    pub max_download_speed: u64,
    /// `None` when the manual limits are in force.
    pub active: Option<ActiveScheduleRule>,
}

/// Local weekday (0 = Monday) and minute-of-day right now.
pub fn local_now() -> (u8, u16) {
    use chrono::{Datelike, Timelike};
    let now = chrono::Local::now();
    let weekday = now.weekday().num_days_from_monday() as u8;
    // `hour()`/`minute()` are 0..=23 / 0..=59, so this cannot exceed 1439.
    let minute = (now.hour() * 60 + now.minute()) as u16;
    (weekday, minute)
}

fn previous_weekday(weekday: u8) -> u8 {
    (weekday + 6) % 7
}

fn day_selected(days: u8, weekday: u8) -> bool {
    weekday < 7 && days & (1 << weekday) != 0
}

/// The rule's window, or `None` when it can never match.
///
/// Clamps rather than trusting the stored numbers. `validate` rejects a bad
/// rule at the IPC boundary, but a hand-edited or downgraded `config.json`
/// reaches evaluation without passing through it, and a nonsense window must
/// read as "no rule" rather than as an all-day throttle.
fn window(rule: &BandwidthScheduleRule) -> Option<(u16, u16)> {
    if !rule.enabled || rule.days & ALL_DAYS == 0 {
        return None;
    }
    let start = rule.start_minute;
    let end = rule.end_minute;
    if start >= MINUTES_PER_DAY || end == 0 || end > MINUTES_PER_DAY || start == end {
        return None;
    }
    Some((start, end))
}

/// Whether `minute` on `weekday` (0 = Monday) falls inside `rule`'s window.
pub fn matches(rule: &BandwidthScheduleRule, weekday: u8, minute: u16) -> bool {
    let Some((start, end)) = window(rule) else {
        return false;
    };
    if start < end {
        day_selected(rule.days, weekday) && minute >= start && minute < end
    } else {
        // Crosses midnight. The tail belongs to the day the window opened, so
        // an early-morning minute is checked against *yesterday's* bit — which
        // is what lets "Mon 22:00 → 06:00" be expressed by selecting Monday
        // alone instead of also having to tick Tuesday.
        (day_selected(rule.days, weekday) && minute >= start)
            || (day_selected(rule.days, previous_weekday(weekday)) && minute < end)
    }
}

/// The first matching rule, or `None` when the manual limits apply.
pub fn active_rule(
    rules: &[BandwidthScheduleRule],
    weekday: u8,
    minute: u16,
) -> Option<&BandwidthScheduleRule> {
    rules.iter().find(|rule| matches(rule, weekday, minute))
}

/// Resolve the caps in force at `(weekday, minute)`.
///
/// `manual_upload` / `manual_download` are the Settings values, used verbatim
/// when the schedule is off or no window is open.
pub fn resolve(
    schedule_enabled: bool,
    rules: &[BandwidthScheduleRule],
    manual_upload: u64,
    manual_download: u64,
    weekday: u8,
    minute: u16,
) -> ResolvedLimits {
    if schedule_enabled {
        if let Some(rule) = active_rule(rules, weekday, minute) {
            return ResolvedLimits {
                max_upload_speed: rule.max_upload_speed,
                max_download_speed: rule.max_download_speed,
                active: Some(ActiveScheduleRule {
                    id: rule.id.clone(),
                    label: rule.label.clone(),
                    end_minute: rule.end_minute,
                }),
            };
        }
    }
    ResolvedLimits {
        max_upload_speed: manual_upload,
        max_download_speed: manual_download,
        active: None,
    }
}

/// [`resolve`] against the persisted settings.
pub fn resolve_settings(
    settings: &crate::types::AppSettings,
    weekday: u8,
    minute: u16,
) -> ResolvedLimits {
    resolve(
        settings.bandwidth_schedule_enabled,
        &settings.bandwidth_schedule,
        settings.max_upload_speed,
        settings.max_download_speed,
        weekday,
        minute,
    )
}

/// What is wrong with a single rule, independent of the list it sits in.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
enum RuleFault {
    Id,
    Label,
    Days,
    Window,
    EmptyWindow,
}

/// The first fault in `rule`, or `None` if it is well-formed.
///
/// The single source of truth for both [`validate`] (which refuses a save) and
/// [`repair`] (which drops the rule on load). Splitting those into two
/// hand-written condition lists is how a rule ends up rejected by one and kept
/// by the other, which would make the config unloadable *and* unsavable.
fn rule_fault(rule: &BandwidthScheduleRule) -> Option<RuleFault> {
    if rule.id.is_empty()
        || rule.id.len() > MAX_RULE_ID_BYTES
        || !rule
            .id
            .bytes()
            .all(|b| b.is_ascii_alphanumeric() || b == b'-' || b == b'_')
    {
        return Some(RuleFault::Id);
    }
    if rule.label.chars().count() > MAX_RULE_LABEL_CHARS {
        return Some(RuleFault::Label);
    }
    if rule.days & ALL_DAYS == 0 || rule.days & !ALL_DAYS != 0 {
        return Some(RuleFault::Days);
    }
    if rule.start_minute >= MINUTES_PER_DAY
        || rule.end_minute == 0
        || rule.end_minute > MINUTES_PER_DAY
    {
        return Some(RuleFault::Window);
    }
    if rule.start_minute == rule.end_minute {
        return Some(RuleFault::EmptyWindow);
    }
    None
}

/// Reject a schedule that cannot mean anything, at the IPC boundary.
///
/// Returns a coded-error envelope so the message localizes like every other
/// settings rejection. Note that a rule is checked even when
/// `bandwidth_schedule_enabled` is false: the list is persisted either way, and
/// refusing it only once the feature is switched on would report the mistake
/// long after it was made.
pub fn validate(rules: &[BandwidthScheduleRule]) -> Result<(), String> {
    use crate::commands::errors::coded;

    if rules.len() > MAX_SCHEDULE_RULES {
        return Err(coded(
            "settings_bandwidth_schedule_too_many",
            format!("At most {MAX_SCHEDULE_RULES} bandwidth schedule rules are allowed"),
        ));
    }
    let mut seen: Vec<&str> = Vec::with_capacity(rules.len());
    for rule in rules {
        if let Some(fault) = rule_fault(rule) {
            return Err(match fault {
                RuleFault::Id => coded(
                    "settings_bandwidth_schedule_invalid_id",
                    "A schedule rule has an invalid identifier",
                ),
                RuleFault::Label => coded(
                    "settings_bandwidth_schedule_label_too_long",
                    format!(
                        "A schedule rule name may be at most {MAX_RULE_LABEL_CHARS} characters"
                    ),
                ),
                RuleFault::Days => coded(
                    "settings_bandwidth_schedule_no_days",
                    "A schedule rule must select at least one day",
                ),
                RuleFault::Window => coded(
                    "settings_bandwidth_schedule_invalid_window",
                    "A schedule rule's times must fall within one day",
                ),
                RuleFault::EmptyWindow => coded(
                    "settings_bandwidth_schedule_empty_window",
                    "A schedule rule's start and end times must differ",
                ),
            });
        }
        if seen.contains(&rule.id.as_str()) {
            return Err(coded(
                "settings_bandwidth_schedule_duplicate_id",
                "Two schedule rules share an identifier",
            ));
        }
        seen.push(rule.id.as_str());
    }
    Ok(())
}

/// Drop the rules a save would refuse, and report whether anything went.
///
/// Called from `soft_repair_settings` on config load. The alternative is what
/// the load path does with a validation failure: back up `config.json` and
/// reset **every** setting to defaults. Trading one hand-edited or
/// downgrade-mangled rule for a user's whole configuration is not a trade worth
/// making, and it costs nothing to be lenient here — [`matches`] already treats
/// a malformed window as inert, so a bad rule was never going to throttle
/// anything.
///
/// Guaranteed to leave a list [`validate`] accepts; the tests pin that.
pub fn repair(rules: &mut Vec<BandwidthScheduleRule>) -> bool {
    let before = rules.len();
    let mut seen: Vec<String> = Vec::with_capacity(before);
    rules.retain(|rule| {
        if let Some(fault) = rule_fault(rule) {
            tracing::warn!(
                "Dropping malformed bandwidth schedule rule {:?} on load ({fault:?})",
                rule.id
            );
            return false;
        }
        if seen.contains(&rule.id) {
            tracing::warn!(
                "Dropping duplicate bandwidth schedule rule {:?} on load",
                rule.id
            );
            return false;
        }
        seen.push(rule.id.clone());
        true
    });
    if rules.len() > MAX_SCHEDULE_RULES {
        tracing::warn!(
            "Truncating bandwidth schedule from {} to {MAX_SCHEDULE_RULES} rules on load",
            rules.len()
        );
        rules.truncate(MAX_SCHEDULE_RULES);
    }
    rules.len() != before
}

#[cfg(test)]
mod tests {
    use super::*;

    const MON: u8 = 0;
    const TUE: u8 = 1;
    const SAT: u8 = 5;
    const SUN: u8 = 6;
    /// Monday through Friday.
    const WEEKDAYS_ONLY: u8 = 0b0001_1111;

    fn day(weekday: u8) -> u8 {
        1 << weekday
    }

    fn rule(days: u8, start: u16, end: u16) -> BandwidthScheduleRule {
        BandwidthScheduleRule {
            id: "r1".to_string(),
            enabled: true,
            label: String::new(),
            days,
            start_minute: start,
            end_minute: end,
            max_upload_speed: 50_000,
            max_download_speed: 500_000,
        }
    }

    #[test]
    fn a_daytime_window_is_half_open() {
        let r = rule(day(MON), 9 * 60, 17 * 60);
        assert!(!matches(&r, MON, 9 * 60 - 1), "a minute before start");
        assert!(matches(&r, MON, 9 * 60), "start is inclusive");
        assert!(matches(&r, MON, 17 * 60 - 1), "last minute inside");
        assert!(!matches(&r, MON, 17 * 60), "end is exclusive");
    }

    /// Back-to-back windows must not both claim the boundary minute, or which
    /// caps apply at 17:00 depends on list order for no reason the user can see.
    #[test]
    fn adjacent_windows_do_not_overlap_at_the_boundary() {
        let morning = rule(ALL_DAYS, 9 * 60, 17 * 60);
        let evening = rule(ALL_DAYS, 17 * 60, 23 * 60);
        assert!(!matches(&morning, TUE, 17 * 60));
        assert!(matches(&evening, TUE, 17 * 60));
    }

    #[test]
    fn a_full_day_window_covers_every_minute() {
        let r = rule(day(SUN), 0, MINUTES_PER_DAY);
        assert!(matches(&r, SUN, 0));
        assert!(matches(&r, SUN, MINUTES_PER_DAY - 1));
        assert!(!matches(&r, SAT, 720), "another weekday is untouched");
    }

    /// The tail of an overnight window belongs to the day it opened, so
    /// selecting Monday alone has to cover Tuesday's small hours. Ticking only
    /// the start day is how a user reads "Mon 22:00 → 06:00".
    #[test]
    fn an_overnight_window_runs_into_the_next_day() {
        let r = rule(day(MON), 22 * 60, 6 * 60);
        assert!(matches(&r, MON, 22 * 60), "opens Monday evening");
        assert!(matches(&r, MON, 23 * 60 + 59), "still Monday at midnight");
        assert!(matches(&r, TUE, 0), "carries past midnight");
        assert!(matches(&r, TUE, 5 * 60 + 59), "last minute of the tail");
        assert!(!matches(&r, TUE, 6 * 60), "end is exclusive");
        assert!(
            !matches(&r, MON, 6 * 60),
            "Monday morning is Sunday's tail, and Sunday is not selected"
        );
    }

    /// The Sunday→Monday wrap is the one that an `if weekday > 0` style
    /// previous-day calculation gets wrong.
    #[test]
    fn an_overnight_window_wraps_from_sunday_into_monday() {
        let r = rule(day(SUN), 23 * 60, 2 * 60);
        assert!(matches(&r, SUN, 23 * 60 + 30));
        assert!(matches(&r, MON, 60), "01:00 Monday is Sunday's tail");
        assert!(!matches(&r, SAT, 60));
    }

    #[test]
    fn a_disabled_or_dayless_rule_never_matches() {
        let mut off = rule(ALL_DAYS, 0, MINUTES_PER_DAY);
        off.enabled = false;
        assert!(!matches(&off, MON, 0));

        let dayless = rule(0, 0, MINUTES_PER_DAY);
        assert!(!matches(&dayless, MON, 0));
    }

    /// A window that survived a hand-edited config must read as "no rule",
    /// never as an all-day throttle the user cannot find in the UI.
    #[test]
    fn nonsense_windows_are_inert_rather_than_all_day() {
        for (start, end) in [
            (0u16, 0u16),
            (600, 600),
            (MINUTES_PER_DAY, 60),
            (60, MINUTES_PER_DAY + 1),
            (60, 0),
        ] {
            let r = rule(ALL_DAYS, start, end);
            for minute in [0u16, 1, 599, 600, 601, 1439] {
                assert!(
                    !matches(&r, MON, minute),
                    "({start},{end}) must not match minute {minute}"
                );
            }
        }
    }

    #[test]
    fn the_first_matching_rule_wins() {
        let mut first = rule(ALL_DAYS, 0, MINUTES_PER_DAY);
        first.id = "first".to_string();
        first.max_upload_speed = 1;
        let mut second = rule(ALL_DAYS, 0, MINUTES_PER_DAY);
        second.id = "second".to_string();
        second.max_upload_speed = 2;

        let resolved = resolve(true, &[first, second], 999, 999, MON, 100);
        assert_eq!(resolved.max_upload_speed, 1);
        assert_eq!(resolved.active.expect("a rule is active").id, "first");
    }

    /// A skipped disabled rule must not shadow a later one that does apply.
    #[test]
    fn a_disabled_rule_does_not_shadow_a_later_match() {
        let mut disabled = rule(ALL_DAYS, 0, MINUTES_PER_DAY);
        disabled.id = "disabled".to_string();
        disabled.enabled = false;
        let mut live = rule(ALL_DAYS, 0, MINUTES_PER_DAY);
        live.id = "live".to_string();

        let resolved = resolve(true, &[disabled, live], 999, 999, MON, 100);
        assert_eq!(resolved.active.expect("a rule is active").id, "live");
    }

    #[test]
    fn manual_limits_apply_when_nothing_is_scheduled() {
        let r = rule(day(SAT), 0, MINUTES_PER_DAY);

        let outside = resolve(true, std::slice::from_ref(&r), 111, 222, MON, 0);
        assert_eq!(
            (outside.max_upload_speed, outside.max_download_speed),
            (111, 222)
        );
        assert!(outside.active.is_none());

        // The whole feature switched off must not consult the rules at all,
        // even for a window that is open right now.
        let disabled = resolve(false, std::slice::from_ref(&r), 111, 222, SAT, 600);
        assert_eq!(
            (disabled.max_upload_speed, disabled.max_download_speed),
            (111, 222)
        );
        assert!(disabled.active.is_none());
    }

    /// Unlimited is `0` in `AppSettings`, so a rule must be able to *raise* the
    /// cap to unlimited and not be mistaken for "no rule".
    #[test]
    fn a_rule_can_schedule_unlimited() {
        let mut r = rule(ALL_DAYS, 0, MINUTES_PER_DAY);
        r.max_upload_speed = 0;
        r.max_download_speed = 0;

        let resolved = resolve(true, &[r], 111, 222, MON, 600);
        assert_eq!(resolved.max_upload_speed, 0);
        assert_eq!(resolved.max_download_speed, 0);
        assert!(
            resolved.active.is_some(),
            "an unlimited rule is still an active rule"
        );
    }

    #[test]
    fn local_now_is_in_range() {
        let (weekday, minute) = local_now();
        assert!(weekday < 7);
        assert!(minute < MINUTES_PER_DAY);
    }

    #[test]
    fn validate_accepts_a_reasonable_timetable() {
        let weekdays = BandwidthScheduleRule {
            id: "weekdays".to_string(),
            enabled: true,
            label: "Work hours".to_string(),
            days: 0b0001_1111,
            start_minute: 9 * 60,
            end_minute: 18 * 60,
            max_upload_speed: 40_000,
            max_download_speed: 400_000,
        };
        let overnight = BandwidthScheduleRule {
            id: "overnight".to_string(),
            days: 0b0111_1111,
            start_minute: 23 * 60,
            end_minute: 7 * 60,
            max_upload_speed: 0,
            max_download_speed: 0,
            ..weekdays.clone()
        };
        assert!(validate(&[weekdays, overnight]).is_ok());
    }

    /// The stable code inside a rejection's coded envelope.
    fn rejection_code(result: Result<(), String>) -> String {
        let raw = result.expect_err("this schedule must be rejected");
        let parsed: serde_json::Value =
            serde_json::from_str(&raw).expect("a rejection is a coded-error envelope");
        parsed["code"]
            .as_str()
            .expect("the envelope carries a code")
            .to_string()
    }

    #[test]
    fn validate_rejects_the_shapes_evaluation_treats_as_inert() {
        let base = rule(ALL_DAYS, 60, 120);
        let with = |patch: fn(&mut BandwidthScheduleRule)| {
            let mut r = base.clone();
            patch(&mut r);
            r
        };

        for (label, rule, expected) in [
            (
                "empty window",
                with(|r| {
                    r.start_minute = 600;
                    r.end_minute = 600;
                }),
                "settings_bandwidth_schedule_empty_window",
            ),
            (
                "no days",
                with(|r| r.days = 0),
                "settings_bandwidth_schedule_no_days",
            ),
            (
                "unknown day bit",
                with(|r| r.days = 0b1000_0001),
                "settings_bandwidth_schedule_no_days",
            ),
            (
                "end past midnight",
                with(|r| r.end_minute = MINUTES_PER_DAY + 1),
                "settings_bandwidth_schedule_invalid_window",
            ),
            (
                "zero end",
                with(|r| r.end_minute = 0),
                "settings_bandwidth_schedule_invalid_window",
            ),
            (
                "start at midnight-end",
                with(|r| r.start_minute = MINUTES_PER_DAY),
                "settings_bandwidth_schedule_invalid_window",
            ),
            (
                "blank id",
                with(|r| r.id = String::new()),
                "settings_bandwidth_schedule_invalid_id",
            ),
            (
                "id with a space",
                with(|r| r.id = "has space".to_string()),
                "settings_bandwidth_schedule_invalid_id",
            ),
            (
                "overlong id",
                with(|r| r.id = "a".repeat(MAX_RULE_ID_BYTES + 1)),
                "settings_bandwidth_schedule_invalid_id",
            ),
            (
                "overlong label",
                with(|r| r.label = "x".repeat(MAX_RULE_LABEL_CHARS + 1)),
                "settings_bandwidth_schedule_label_too_long",
            ),
        ] {
            assert_eq!(rejection_code(validate(&[rule])), expected, "{label}");
        }

        assert_eq!(
            rejection_code(validate(&[base.clone(), base.clone()])),
            "settings_bandwidth_schedule_duplicate_id"
        );

        let many: Vec<BandwidthScheduleRule> = (0..=MAX_SCHEDULE_RULES)
            .map(|n| BandwidthScheduleRule {
                id: format!("r{n}"),
                ..base.clone()
            })
            .collect();
        assert_eq!(
            rejection_code(validate(&many)),
            "settings_bandwidth_schedule_too_many"
        );
    }

    /// A disabled rule is still stored, so it still has to be well-formed —
    /// otherwise re-enabling it later fails a save the user cannot connect to
    /// the toggle they just flipped.
    #[test]
    fn validate_checks_disabled_rules_too() {
        let mut r = rule(ALL_DAYS, 600, 600);
        r.enabled = false;
        assert!(validate(&[r]).is_err());
    }

    /// The load path's alternative to repairing is backing up `config.json`
    /// and resetting every setting, so whatever `repair` returns has to be
    /// something `validate` takes — for *any* input, not just the shapes
    /// enumerated below.
    #[test]
    fn repair_always_leaves_a_schedule_validate_accepts() {
        let base = rule(ALL_DAYS, 60, 120);
        let broken = [
            BandwidthScheduleRule {
                id: String::new(),
                ..base.clone()
            },
            BandwidthScheduleRule {
                id: "bad id".to_string(),
                ..base.clone()
            },
            BandwidthScheduleRule {
                id: "a".repeat(MAX_RULE_ID_BYTES + 1),
                ..base.clone()
            },
            BandwidthScheduleRule {
                id: "dup".to_string(),
                ..base.clone()
            },
            BandwidthScheduleRule {
                id: "dup".to_string(),
                ..base.clone()
            },
            BandwidthScheduleRule {
                id: "nodays".to_string(),
                days: 0,
                ..base.clone()
            },
            BandwidthScheduleRule {
                id: "empty".to_string(),
                start_minute: 600,
                end_minute: 600,
                ..base.clone()
            },
            BandwidthScheduleRule {
                id: "window".to_string(),
                end_minute: MINUTES_PER_DAY + 1,
                ..base.clone()
            },
            BandwidthScheduleRule {
                id: "label".to_string(),
                label: "x".repeat(MAX_RULE_LABEL_CHARS + 1),
                ..base.clone()
            },
        ];

        let mut rules = broken.to_vec();
        assert!(repair(&mut rules), "malformed rules must be reported");
        assert!(validate(&rules).is_ok(), "repaired: {rules:?}");
        // Exactly the first "dup" survives — every other entry has a fault.
        assert_eq!(rules.len(), 1);
        assert_eq!(rules[0].id, "dup");
    }

    #[test]
    fn repair_leaves_a_good_schedule_untouched() {
        let a = BandwidthScheduleRule {
            id: "a".to_string(),
            ..rule(WEEKDAYS_ONLY, 9 * 60, 18 * 60)
        };
        let b = BandwidthScheduleRule {
            id: "b".to_string(),
            ..rule(ALL_DAYS, 23 * 60, 7 * 60)
        };
        let mut rules = vec![a.clone(), b.clone()];
        assert!(!repair(&mut rules), "nothing to repair");
        assert_eq!(rules, vec![a, b]);
    }

    #[test]
    fn repair_truncates_past_the_cap() {
        let base = rule(ALL_DAYS, 60, 120);
        let mut rules: Vec<BandwidthScheduleRule> = (0..MAX_SCHEDULE_RULES + 5)
            .map(|n| BandwidthScheduleRule {
                id: format!("r{n}"),
                ..base.clone()
            })
            .collect();
        assert!(repair(&mut rules));
        assert_eq!(rules.len(), MAX_SCHEDULE_RULES);
        assert!(validate(&rules).is_ok());
    }

    /// Every fault the refusal path can name must also be a fault the repair
    /// path drops, or a config becomes both unloadable and unsavable.
    #[test]
    fn validate_and_repair_agree_on_what_is_broken() {
        let base = rule(ALL_DAYS, 60, 120);
        for patch in [
            |r: &mut BandwidthScheduleRule| r.id = String::new(),
            |r: &mut BandwidthScheduleRule| r.id = "no spaces allowed".to_string(),
            |r: &mut BandwidthScheduleRule| r.days = 0,
            |r: &mut BandwidthScheduleRule| r.days = 0b1000_0000,
            |r: &mut BandwidthScheduleRule| r.end_minute = r.start_minute,
            |r: &mut BandwidthScheduleRule| r.end_minute = 0,
            |r: &mut BandwidthScheduleRule| r.start_minute = MINUTES_PER_DAY,
            |r: &mut BandwidthScheduleRule| r.label = "x".repeat(MAX_RULE_LABEL_CHARS + 1),
        ] {
            let mut broken = base.clone();
            patch(&mut broken);
            assert!(
                validate(std::slice::from_ref(&broken)).is_err(),
                "validate must refuse {broken:?}"
            );
            let mut rules = vec![broken.clone()];
            assert!(repair(&mut rules), "repair must drop {broken:?}");
            assert!(rules.is_empty());
        }
    }

    /// Every label a translator can produce has to survive the character cap,
    /// which counts characters rather than bytes so a CJK name is not cut to a
    /// third of the length an ASCII one gets.
    #[test]
    fn the_label_cap_counts_characters_not_bytes() {
        let mut r = rule(ALL_DAYS, 60, 120);
        r.label = "夜".repeat(MAX_RULE_LABEL_CHARS);
        assert!(validate(std::slice::from_ref(&r)).is_ok());
        r.label = "夜".repeat(MAX_RULE_LABEL_CHARS + 1);
        assert!(validate(&[r]).is_err());
    }
}
